version: '3.7'
x-extra_hosts:
   &default-extra_hosts
      - "mysql:192.168.1.20"
x-oracle_network:
   &oracle_network
           ./config/oracle-instanceclient/network:/usr/lib/oracle/21/client64/lib/network
services:
   memcached:
      image: docker.io/memcached
      restart: unless-stopped
   nginx:
      depends_on:
         - php
         - memcached
      image: docker.io/nginx:alpine
      ports:
         - "8080:8080"
      user: "1000:1000"
      volumes:
         - ./logs:/var/log/nginx
         - ./run:/var/run
         - ./cache:/var/cache/nginx
         - ./config/nginx/conf.d:/etc/nginx/conf.d
         - ./app:/var/www/html
      extra_hosts: *default-extra_hosts
      restart: unless-stopped
   php:
      build: images/php-alpine-oci8
      user: "1000:1000"
      volumes:
         - ./config/php/php-fpm.d:/usr/local/etc/php-fpm.d
         - ./logs:/usr/local/var/log
         - ./app:/var/www/html
         - *oracle_network
      extra_hosts: *default-extra_hosts
      restart: unless-stopped
